const questions = [
  // --- PAÍSES E GEOGRAFIA ---
  { question: "Qual é a capital da França?", answers: [{ text: "Londres", correct: false }, { text: "Paris", correct: true }, { text: "Madri", correct: false }, { text: "Roma", correct: false }] },
  { question: "Qual é o maior país do mundo em área territorial?", answers: [{ text: "Canadá", correct: false }, { text: "Rússia", correct: true }, { text: "China", correct: false }, { text: "EUA", correct: false }] },
  { question: "Qual país é conhecido como a Terra do Sol Nascente?", answers: [{ text: "China", correct: false }, { text: "Japão", correct: true }, { text: "Coreia do Sul", correct: false }, { text: "Tailândia", correct: false }] },
  { question: "Qual é a capital do Egito?", answers: [{ text: "Cairo", correct: true }, { text: "Alexandria", correct: false }, { text: "Giza", correct: false }, { text: "Luxor", correct: false }] },
  { question: "Em qual continente fica a Austrália?", answers: [{ text: "Ásia", correct: false }, { text: "Oceania", correct: true }, { text: "Europa", correct: false }, { text: "África", correct: false }] },
  { question: "Qual é o maior oceano do mundo?", answers: [{ text: "Atlântico", correct: false }, { text: "Pacífico", correct: true }, { text: "Índico", correct: false }, { text: "Glacial Ártico", correct: false }] },
  { question: "Qual é a capital da Austrália?", answers: [{ text: "Sydney", correct: false }, { text: "Melbourne", correct: false }, { text: "Camberra", correct: true }, { text: "Brisbane", correct: false }] },
  { question: "Qual país tem o maior número de habitantes?", answers: [{ text: "Índia", correct: true }, { text: "China", correct: false }, { text: "EUA", correct: false }, { text: "Brasil", correct: false }] },
  { question: "Qual é o menor país do mundo?", answers: [{ text: "Mônaco", correct: false }, { text: "Vaticano", correct: true }, { text: "San Marino", correct: false }, { text: "Malta", correct: false }] },
  { question: "Qual é a capital do Canadá?", answers: [{ text: "Toronto", correct: false }, { text: "Vancouver", correct: false }, { text: "Ottawa", correct: true }, { text: "Montreal", correct: false }] },
  { question: "Qual país sul-americano não faz fronteira com o Brasil?", answers: [{ text: "Argentina", correct: false }, { text: "Chile", correct: true }, { text: "Colômbia", correct: false }, { text: "Peru", correct: false }] },
  { question: "Em qual país fica a cidade de Istambul?", answers: [{ text: "Grécia", correct: false }, { text: "Turquia", correct: true }, { text: "Egito", correct: false }, { text: "Irã", correct: false }] },
  { question: "Qual é a capital da Alemanha?", answers: [{ text: "Munique", correct: false }, { text: "Berlim", correct: true }, { text: "Frankfurt", correct: false }, { text: "Hamburgo", correct: false }] },
  { question: "Monte Everest está localizado em qual cadeia de montanhas?", answers: [{ text: "Andes", correct: false }, { text: "Himalaia", correct: true }, { text: "Alpes", correct: false }, { text: "Rochosas", correct: false }] },
  { question: "Qual país é famoso pela forma do seu mapa parecer uma bota?", answers: [{ text: "Espanha", correct: false }, { text: "Itália", correct: true }, { text: "Portugal", correct: false }, { text: "Grécia", correct: false }] },
  { question: "Qual é a capital da Argentina?", answers: [{ text: "Buenos Aires", correct: true }, { text: "Córdoba", correct: false }, { text: "Rosário", correct: false }, { text: "Mendoza", correct: false }] },
  { question: "Em qual país fica o Machu Picchu?", answers: [{ text: "Chile", correct: false }, { text: "Peru", correct: true }, { text: "Bolívia", correct: false }, { text: "Equador", correct: false }] },
  { question: "Qual é a capital da Espanha?", answers: [{ text: "Barcelona", correct: false }, { text: "Madri", correct: true }, { text: "Sevilha", correct: false }, { text: "Valência", correct: false }] },
  { question: "Qual rio é considerado o mais extenso do mundo?", answers: [{ text: "Nilo", correct: false }, { text: "Amazonas", correct: true }, { text: "Mississippi", correct: false }, { text: "Yangtzé", correct: false }] },
  { question: "Qual é o país com mais ilhas no mundo?", answers: [{ text: "Finlândia", correct: false }, { text: "Suécia", correct: true }, { text: "Indonésia", correct: false }, { text: "Filipinas", correct: false }] },
  { question: "Qual é a capital da Coreia do Sul?", answers: [{ text: "Tóquio", correct: false }, { text: "Seul", correct: true }, { text: "Pequim", correct: false }, { text: "Bangcoc", correct: false }] },
  { question: "Qual país possui o formato de um arquipélago no Sudeste Asiático com mais de 17 mil ilhas?", answers: [{ text: "Filipinas", correct: false }, { text: "Indonésia", correct: true }, { text: "Japão", correct: false }, { text: "Malásia", correct: false }] },
  { question: "Qual é a capital da Colômbia?", answers: [{ text: "Medellín", correct: false }, { text: "Bogotá", correct: true }, { text: "Cali", correct: false }, { text: "Cartagena", correct: false }] },
  { question: "Em qual país fica o Taj Mahal?", answers: [{ text: "Índia", correct: true }, { text: "Paquistão", correct: false }, { text: "Bangladesh", correct: false }, { text: "Nepal", correct: false }] },
  { question: "Qual país tem o vermelho, branco e azul na sua bandeira e sua capital é Amsterdã?", answers: [{ text: "Bélgica", correct: false }, { text: "Países Baixos", correct: true }, { text: "Dinamarca", correct: false }, { text: "Suíça", correct: false }] },

  // --- MATEMÁTICA BÁSICA ---
  { question: "Quanto é 7 x 8?", answers: [{ text: "54", correct: false }, { text: "56", correct: true }, { text: "64", correct: false }, { text: "48", correct: false }] },
  { question: "Quanto é a raiz quadrada de 144?", answers: [{ text: "10", correct: false }, { text: "12", correct: true }, { text: "14", correct: false }, { text: "16", correct: false }] },
  { question: "Quanto é 15% de 200?", answers: [{ text: "30", correct: true }, { text: "20", correct: false }, { text: "25", correct: false }, { text: "35", correct: false }] },
  { question: "Qual é o resultado de 9 x 9 - 10?", answers: [{ text: "71", correct: true }, { text: "81", correct: false }, { text: "70", correct: false }, { text: "80", correct: false }] },
  { question: "Se um triângulo tem lados de 3cm, 4cm e 5cm, qual é o seu perímetro?", answers: [{ text: "12 cm", correct: true }, { text: "15 cm", correct: false }, { text: "20 cm", correct: false }, { text: "9 cm", correct: false }] },
  { question: "Quanto é 120 dividido por 4?", answers: [{ text: "25", correct: false }, { text: "30", correct: true }, { text: "35", correct: false }, { text: "40", correct: false }] },
  { question: "Qual é o único número primo par?", answers: [{ text: "0", correct: false }, { text: "2", correct: true }, { text: "4", correct: false }, { text: "1", correct: false }] },
  { question: "Quanto é 2 elevado à quinta potência (2^5)?", answers: [{ text: "16", correct: false }, { text: "32", correct: true }, { text: "64", correct: false }, { text: "10", correct: false }] },
  { question: "Qual é a soma dos ângulos internos de um triângulo?", answers: [{ text: "90°", correct: false }, { text: "180°", correct: true }, { text: "360°", correct: false }, { text: "270°", correct: false }] },
  { question: "Quanto é 50 x 40?", answers: [{ text: "200", correct: false }, { text: "2000", correct: true }, { text: "20000", correct: false }, { text: "4000", correct: false }] },
  { question: "Quanto é 100 - 37?", answers: [{ text: "63", correct: true }, { text: "73", correct: false }, { text: "53", correct: false }, { text: "67", correct: false }] },
  { question: "Se Pedro tem 3 dúzias de ovos, quantos ovos ele tem?", answers: [{ text: "30", correct: false }, { text: "36", correct: true }, { text: "24", correct: false }, { text: "40", correct: false }] },
  { question: "Quanto é a metade de 3/4?", answers: [{ text: "3/8", correct: true }, { text: "3/2", correct: false }, { text: "1/4", correct: false }, { text: "6/4", correct: false }] },
  { question: "Qual o valor de X em: 2x + 4 = 12?", answers: [{ text: "3", correct: false }, { text: "4", correct: true }, { text: "2", correct: false }, { text: "6", correct: false }] },
  { question: "Quanto é 99 + 101?", answers: [{ text: "190", correct: false }, { text: "200", correct: true }, { text: "210", correct: false }, { text: "199", correct: false }] },
  { question: "Qual é a raiz quadrada de 81?", answers: [{ text: "7", correct: false }, { text: "8", correct: false }, { text: "9", correct: true }, { text: "10", correct: false }] },
  { question: "Se um quadrado tem lado de 6 cm, qual é a sua área?", answers: [{ text: "24 cm²", correct: false }, { text: "36 cm²", correct: true }, { text: "12 cm²", correct: false }, { text: "18 cm²", correct: false }] },
  { question: "Quanto é 7 x 7?", answers: [{ text: "42", correct: false }, { text: "49", correct: true }, { text: "56", correct: false }, { text: "36", correct: false }] },
  { question: "Qual é o valor do número Pi (π) aproximado?", answers: [{ text: "3,14", correct: true }, { text: "2,71", correct: false }, { text: "1,41", correct: false }, { text: "3,50", correct: false }] },
  { question: "Quanto é 500 dividido por 5?", answers: [{ text: "50", correct: false }, { text: "100", correct: true }, { text: "200", correct: false }, { text: "150", correct: false }] },
  { question: "Qual o resultado de 10 - 2 x 3? (Lembre-se da ordem das operações)", answers: [{ text: "24", correct: false }, { text: "4", correct: true }, { text: "16", correct: false }, { text: "8", correct: false }] },
  { question: "Quanto é 13 x 3?", answers: [{ text: "36", correct: false }, { text: "39", correct: true }, { text: "42", correct: false }, { text: "33", correct: false }] },
  { question: "Se você comprar um produto de R$ 80 com 25% de desconto, quanto paga?", answers: [{ text: "R$ 60", correct: true }, { text: "R$ 50", correct: false }, { text: "R$ 70", correct: false }, { text: "R$ 65", correct: false }] },
  { question: "Qual é o triplo de 15?", answers: [{ text: "30", correct: false }, { text: "45", correct: true }, { text: "60", correct: false }, { text: "35", correct: false }] },
  { question: "Quanto é 1000 - 450?", answers: [{ text: "550", correct: true }, { text: "650", correct: false }, { text: "450", correct: false }, { text: "500", correct: false }] },

  // --- CONHECIMENTOS GERAIS E CIÊNCIAS ---
  { question: "Qual é o elemento químico com o símbolo 'O'?", answers: [{ text: "Ouro", correct: false }, { text: "Oxigênio", correct: true }, { text: "Osmiro", correct: false }, { text: "Ozônio", correct: false }] },
  { question: "Qual é o maior planeta do Sistema Solar?", answers: [{ text: "Saturno", correct: false }, { text: "Júpiter", correct: true }, { text: "Júpiter", correct: false }, { text: "Netuno", correct: false }] },
  { question: "Quantos ossos tem o corpo humano adulto?", answers: [{ text: "206", correct: true }, { text: "180", correct: false }, { text: "210", correct: false }, { text: "300", correct: false }] },
  { question: "Qual gás os humanos consomem na respiração para sobreviver?", answers: [{ text: "Gás Carbônico", correct: false }, { text: "Oxigênio", correct: true }, { text: "Nitrogênio", correct: false }, { text: "Hélio", correct: false }] },
  { question: "Quantas cores tem o arco-íris?", answers: [{ text: "5", correct: false }, { text: "6", correct: false }, { text: "7", correct: true }, { text: "8", correct: false }] },
  { question: "Qual é a velocidade aproximada da luz?", answers: [{ text: "300.000 km/s", correct: true }, { text: "150.000 km/s", correct: false }, { text: "1.000.000 km/s", correct: false }, { text: "30.000 km/s", correct: false }] },
  { question: "Qual é o metal cujo símbolo químico é Au?", answers: [{ text: "Prata", correct: false }, { text: "Ouro", correct: true }, { text: "Cobre", correct: false }, { text: "Alumínio", correct: false }] },
  { question: "Qual é o planeta mais próximo do Sol?", answers: [{ text: "Vênus", correct: false }, { text: "Mercúrio", correct: true }, { text: "Marte", correct: false }, { text: "Terra", correct: false }] },
  { question: "Qual animal é conhecido como o 'Rei da Selva'?", answers: [{ text: "Tigre", correct: false }, { text: "Leão", correct: true }, { text: "Elefante", correct: false }, { text: "Leopardo", correct: false }] },
  { question: "Em que estado da matéria a água se encontra na forma de gelo?", answers: [{ text: "Líquido", correct: false }, { text: "Sólido", correct: true }, { text: "Gasoso", correct: false }, { text: "Plasma", correct: false }] },
  { question: "Quem pintou a Mona Lisa?", answers: [{ text: "Vincent van Gogh", correct: false }, { text: "Leonardo da Vinci", correct: true }, { text: "Pablo Picasso", correct: false }, { text: "Michelangelo", correct: false }] },
  { question: "Quantos dias tem um ano bissexto?", answers: [{ text: "365", correct: false }, { text: "366", correct: true }, { text: "364", correct: false }, { text: "367", correct: false }] },
  { question: "Qual é a estrela mais próxima da Terra?", answers: [{ text: "Alfa Centauri", correct: false }, { text: "Sol", correct: true }, { text: "Sírius", correct: false }, { text: "Betelgeuse", correct: false }] },
  { question: "Qual instrumento é utilizado para medir a temperatura?", answers: [{ text: "Barômetro", correct: false }, { text: "Termômetro", correct: true }, { text: "Higrômetro", correct: false }, { text: "Anemômetro", correct: false }] },
  { question: "Em qual ano o homem pisou na Lua pela primeira vez?", answers: [{ text: "1969", correct: true }, { text: "1975", correct: false }, { text: "1959", correct: false }, { text: "1980", correct: false }] },

  // --- MAIS PAÍSES E GEOGRAFIA ---
  { question: "Qual é a capital dos Estados Unidos?", answers: [{ text: "Nova York", correct: false }, { text: "Washington, D.C.", correct: true }, { text: "Los Angeles", correct: false }, { text: "Chicago", correct: false }] },
  { question: "Qual é a capital da China?", answers: [{ text: "Xangai", correct: false }, { text: "Pequim", correct: true }, { text: "Hong Kong", correct: false }, { text: "Guangzhou", correct: false }] },
  { question: "Qual país é famoso pelos seus canais e gôndolas em Veneza?", answers: [{ text: "França", correct: false }, { text: "Itália", correct: true }, { text: "Espanha", correct: false }, { text: "Grécia", correct: false }] },
  { question: "Qual é a capital do Japão?", answers: [{ text: "Quioto", correct: false }, { text: "Tóquio", correct: true }, { text: "Osaka", correct: false }, { text: "Hiroshima", correct: false }] },
  { question: "Em qual continente fica o Egito?", answers: [{ text: "Ásia", correct: false }, { text: "África", correct: true }, { text: "Europa", correct: false }, { text: "América", correct: false }] },
  { question: "Qual é a capital de Portugal?", answers: [{ text: "Porto", correct: false }, { text: "Lisboa", correct: true }, { text: "Coimbra", correct: false }, { text: "Faro", correct: false }] },
  { question: "Qual país tem a bandeira verde e amarela com um globo azul no centro?", answers: [{ text: "Brasil", correct: true }, { text: "Jamaica", correct: false }, { text: "África do Sul", correct: false }, { text: "Austrália", correct: false }] },
  { question: "Qual é a capital da Itália?", answers: [{ text: "Milão", correct: false }, { text: "Roma", correct: true }, { text: "Napoles", correct: false }, { text: "Florença", correct: false }] },
  { question: "Qual é a moeda oficial do Japão?", answers: [{ text: "Yuan", correct: false }, { text: "Iene", correct: true }, { text: "Won", correct: false }, { text: "Dólar", correct: false }] },
  { question: "Qual é a capital da Rússia?", answers: [{ text: "Moscou", correct: true }, { text: "São Petersburgo", correct: false }, { text: "Kazan", correct: false }, { text: "Sochi", correct: false }] },
  { question: "Qual oceano banha a costa leste do Brasil?", answers: [{ text: "Pacífico", correct: false }, { text: "Atlântico", correct: true }, { text: "Índico", correct: false }, { text: "Glacial Antártico", correct: false }] },
  { question: "Qual é a capital da Holanda (Países Baixos)?", answers: [{ text: "Roterdã", correct: false }, { text: "Amsterdã", correct: true }, { text: "Haia", correct: false }, { text: "Utrecht", correct: false }] },
  { question: "Qual país é famoso pela construção das Grandes Pirâmides?", answers: [{ text: "Grécia", correct: false }, { text: "Egito", correct: true }, { text: "México", correct: false }, { text: "Iraque", correct: false }] },

  // --- MAIS MATEMÁTICA ---
  { question: "Quanto é 8 x 9?", answers: [{ text: "72", correct: true }, { text: "64", correct: false }, { text: "81", correct: false }, { text: "63", correct: false }] },
  { question: "Quanto é 100 dividido por 4?", answers: [{ text: "20", correct: false }, { text: "25", correct: true }, { text: "30", correct: false }, { text: "15", correct: false }] },
  { question: "Se um relógio marca 3 horas, qual é o ângulo entre os ponteiros?", answers: [{ text: "45°", correct: false }, { text: "90°", correct: true }, { text: "120°", correct: false }, { text: "180°", correct: false }] }]
